SELECT C.NAME, C.POPULATION
FROM country C
WHERE (C.REGION='North America' OR C.REGION='Africa')
AND C.YEAR=2006
AND C.POPULATION <> 0
ORDER BY C.POPULATION DESC
FETCH FIRST 10 ROWS ONLY;

SELECT C.NAME, C.POPULATION
FROM country C
WHERE C.REGION='Europe'
AND C.POPULATION > 3500000
AND C.YEAR=2008
FETCH FIRST 10 ROWS ONLY;

SELECT DISTINCT C.NAME
FROM country C
WHERE C.NAME LIKE 'B%'
OR C.NAME LIKE 'N%'
FETCH FIRST 10 ROWS ONLY;

SELECT Count(C.NAME), AVG(C.GDP)
FROM country C
WHERE C.REGION='Asia'
AND YEAR='2011';

SELECT C.REGION
FROM country C
WHERE C.YEAR = 2008
AND C.GDP > .1
GROUP BY C.REGION
HAVING Count(*) >= 3;

INSERT INTO country (name,year,region,area,population,gdp) VALUES ('MyNewCountry',2011,'Africa',75,50,0.09);

UPDATE country
SET area = 150
WHERE area < 150;

UPDATE country C
SET GDP = (SELECT AVG(C.GDP) FROM country C1 WHERE C1.REGION=C.REGION)
WHERE GDP = 0 OR GDP = NULL;

DELETE FROM country WHERE POPULATION=NULL;
